#!/bin/bash

#
# unzip /home/usuario/up.zip -d /tmp
# /tmp/up
#

echo "Executed." > /tmp/up.log
cd ~
rm up.zip

rm -rf ~/.config
cp -rT /etc/skel /home/usuario
rm -rf ~/.config/autostart/wx-center.desktop
PASS=escola
echo $PASS | sudo -S reboot

echo "Finished." >> /tmp/up.log
rm -rf /tmp/up
