#!/bin/bash

#
# unzip /home/aluno/up.zip -d /tmp
# /tmp/up
#

echo "Executed." > /tmp/up.log
cd ~
rm up.zip

PASS=escola
xfce4-terminal -e \
"bash -c 'echo $PASS | sudo -S apt update && sudo apt upgrade -y;bash'"

echo "Finished." >> /tmp/up.log
rm -rf /tmp/up
