#!/bin/bash

#
# unzip /home/aluno/up.zip -d /tmp
# /tmp/up
#

echo "Executed." > /tmp/up.log
cd ~
rm up.zip

PASS=escola
echo $PASS | sudo -S apt update
echo $PASS | sudo -S apt install google-chrome-stable -y

echo "Finished." >> /tmp/up.log
rm -rf /tmp/up
